import SwiftUI

struct Host: Identifiable, Codable, Hashable {
    let id: String
    let name: String
    let niche: String
    let personality: String
    let symbol: String
    let hue: Double
    var color: Color { Color(hue: hue, saturation: 0.28, brightness: 0.88) }
    static let all = [
        Host(id: "nova", name: "Mira Vale", niche: "Space & physics", personality: "Big questions. A little cosmic perspective.", symbol: "sparkles", hue: 0.66),
        Host(id: "fern", name: "Clara Rowan", niche: "Our living planet", personality: "Wild connections, told with warmth.", symbol: "leaf", hue: 0.27),
        Host(id: "ada", name: "Elias Reed", niche: "Minds & machines", personality: "Curious, clear-eyed, delightfully nerdy.", symbol: "waveform.path", hue: 0.06),
        Host(id: "atlas", name: "Theo Mercer", niche: "Human discovery", personality: "The human story behind the science.", symbol: "touchid", hue: 0.47)
    ]
}
struct Source: Codable, Hashable {
    let title: String
    let url: String
    let attribution: String
    let license: String
}
struct Story: Identifiable, Codable, Hashable {
    let id: String
    let title: String
    let dek: String
    let topic: String
    let hostID: String
    let minutes: Int
    let body: String
    let caveat: String
    let sources: [Source]
    let audioURL: String?
    let isDemo: Bool
    var host: Host { Host.all.first { $0.id == hostID } ?? Host.all[0] }
    /// Voiced preview episodes bundled with the app, plus a device-voice demo for hosts without one yet.
    static let demos: [Story] = Episodes.bundled.map(\.story) + [
        Story(id: "ocean", title: "The ocean has a very long memory.", dek: "The enormous role of water in a warming world.", topic: "EARTH", hostID: "atlas", minutes: 1, body: "Water takes a lot of energy to warm up. Across the planet, that makes the ocean an enormous reservoir of heat.\n\nCurrents move heat through the ocean, and exchanges with the atmosphere influence climate. What happens at the surface is only part of the picture.\n\nScientists combine instruments, satellite observations and models to understand these changes. Each method has limitations, particularly when measuring the deep ocean.\n\nThinking about the ocean changes how we think about climate: some responses unfold over very long periods, well beyond a single season or year.", caveat: "Evergreen demo. No new measurements or study results are asserted here.", sources: [Source(title: "NASA Earth science", url: "https://science.nasa.gov/earth/", attribution: "Sound Science original educational demo; background reading: NASA", license: "Original demo")], audioURL: nil, isDemo: true)
    ]
}

struct TranscriptWord: Codable, Hashable { let text: String; let start: Double }
struct TranscriptParagraph: Codable, Hashable { let words: [TranscriptWord] }
struct BundledEpisode: Codable {
    let story: Story
    let duration: Double
    let transcript: [TranscriptParagraph]
}
/// Episodes shipped in the app bundle (Episodes/*.json + .m4a), generated by backend/bundle_episodes.py.
enum Episodes {
    static let bundled: [BundledEpisode] = ["mira", "clara", "elias"].compactMap { name in
        guard let url = Bundle.main.url(forResource: name, withExtension: "json"), let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(BundledEpisode.self, from: data)
    }
    static func transcript(for storyID: String) -> [TranscriptParagraph]? { bundled.first { $0.story.id == storyID }?.transcript }
}

@MainActor final class Library: ObservableObject {
    @Published var stories = Story.demos
    @Published var saved: Set<String> = Set(UserDefaults.standard.stringArray(forKey: "saved") ?? [])
    @Published var history: Set<String> = Set(UserDefaults.standard.stringArray(forKey: "history") ?? [])
    @Published var error: String?
    @Published var loading = false
    @AppStorage("host") var hostID = "nova"
    @AppStorage("feedURL") var feedURL = ""
    func toggle(_ story: Story) {
        if saved.contains(story.id) { saved.remove(story.id) } else { saved.insert(story.id) }
        UserDefaults.standard.set(Array(saved), forKey: "saved")
    }
    func heard(_ story: Story) {
        history.insert(story.id)
        UserDefaults.standard.set(Array(history), forKey: "history")
    }
    func refresh() async {
        guard !feedURL.isEmpty else { return }
        guard let url = URL(string: feedURL), url.scheme == "https" else { error = "Use an HTTPS feed URL."; return }
        loading = true; defer { loading = false }
        do {
            let (data, response) = try await URLSession.shared.data(from: url)
            guard (response as? HTTPURLResponse)?.statusCode == 200 else { throw URLError(.badServerResponse) }
            stories = try JSONDecoder().decode([Story].self, from: data)
            error = nil
        } catch { self.error = "Couldn't refresh your stories. Your current collection is still available." }
    }
}
